<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Data Tables for Orchard Core - Samples</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2020, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Data Tables for Orchard Core - Samples: Sample content that demonstrates the features of Lombiq Data Tables for Orchard Core. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;DataTables;Vue.js</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Data-Tables</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Data-Tables/blob/dev/Lombiq.DataTables.Samples/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentFields" Version="3.0.0-preview-18907" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18907" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.DataTables\Lombiq.DataTables.csproj" />
  </ItemGroup>

</Project>
