<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Data Tables for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2020, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Data Tables for Orchard Core: An Orchard Core wrapper around the DataTables (https://datatables.net/) library for displaying tabular data from custom data sources. It lets you replace HTML tables with a tag helper or create asynchronous, sortable, searchable server-side generated tables. It also includes a pure Vue.js module that works similarly to DataTables. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;DataTables;Vue.js</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Data-Tables</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Data-Tables</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Include="..\renovate.json5" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
    <PackageReference Include="Nito.AsyncEx.Tasks" Version="5.1.2" />
    <PackageReference Include="OrchardCore.Contents" Version="3.0.0-preview-18975" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18975" GeneratePathProperty="true" />
    <PackageReference Include="OrchardCore.Lucene" Version="3.0.0-preview-18975" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.LinqToDb\Lombiq.HelpfulLibraries.LinqToDb.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.LinqToDb" Version="12.6.1-alpha.7.osoe-925" />
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.7.osoe-925" />
    <PackageReference Include="Lombiq.MSBuild.LibMan.Targets" Version="1.0.0-alpha.12.nest-643" />
    <PackageReference Include="Lombiq.HelpfulLibraries.Attributes" Version="12.6.1-alpha.7.osoe-925" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    <PackageReference Include="Lombiq.HelpfulLibraries.SourceGenerators" Version="12.6.1-alpha.7.osoe-925" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'"/>

</Project>
